baseURL: "https://lizicai.com"
title: æå­èœLizicai
paginate: 8
theme: papermod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - identifier: search
                  name: ğŸ”
                  url: /search/
                  weight: 1
                - identifier: mac
                  name: Mac
                  url: /categories/mac/
                  weight: 10
                - identifier: windows
                  name: Windows
                  url: /categories/windows/
                  weight: 20
                - identifier: linux
                  name: Linux
                  url: /categories/linux/
                  weight: 30
                - identifier: tags
                  name: æ ‡ç­¾
                  url: /tags/
                  weight: 50
                - identifier: categories
                  name: åˆ†ç±»
                  url: /categories/
                  weight: 60
                - identifier: series
                  name: ç³»åˆ—
                  url: /series/
                  weight: 61
                - identifier: archives
                  name: å½’æ¡£
                  url: /archives/
                  weight: 62
                - identifier: about
                  name: å…³äºæˆ‘
                  url: /about/
                  weight: 90
    #fr:
        #languageName: ":fr:"
        #languageAltTitle: French
        #weight: 2
        #title: PaperModL2
        #profileMode:
            #enabled: true
            #title: PaperMod
            ## imageUrl: "#"
            ## imageTitle: my image
            ## imageWidth: 120
            ## imageHeight: 120
            #subtitle: "â˜„ï¸ Fast | â˜ï¸ Fluent | ğŸŒ™ Smooth | ğŸ“± Responsive"
            #buttons:
                #- name: Blog
                  #url: posts
                #- name: Tags
                  #url: tags
        #menu:
            #main:
                #- name: Archive
                  #url: archives/
                  #weight: 5
                #- name: Tags
                  #url: tags
                  #weight: 10
                #- name: Categories
                  #url: categories
                  #weight: 10
                #- name: Series
                  #url: series
                  #weight: 10
                #- name: NullLink
                  #url: "#"
                #- name: NullLink2
                  #url: "#"
                #- name: NullLink3
                  #url: "#"

    #fa:
        #languagedirection: rtl
        #weight: 3
        #title: PaperMod RTL
        #homeInfoParams:
            #Title: "Hi there \U0001F44B"
            #Content: Welcome to RTL layout
        #menu:
            #main:
                #- name: Tags
                  #url: tags
                  #weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    #env: development # to enable google analytics, opengraph, twitter-cards and schema.
    #description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    description: "æå­èœLizicaiåšå®¢, mac, macè½¯ä»¶åˆ†äº«, è‹¹æœç”µè„‘è½¯ä»¶åˆ†äº«,windows, windowsè½¯ä»¶åˆ†äº«, linux, linuxè½¯ä»¶åˆ†äº«,iPhone, iPhone APPä½¿ç”¨åˆ†äº«"
    Title: æå­èœLizicai
    author: Lizicai
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    #comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon.ico"
        favicon32x32: "/favicon.ico"
        apple_touch_icon: "/apple-touch-icon.png"
        safari_pinned_tab: "/apple-touch-icon.png"

    label:
        text: "æå­èœ Lizicai"
        icon: /apple-touch-icon.png
        iconHeight: 32

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page
    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: æå­èœ Lizicai
        subtitle: "æå­èœçš„ä¸ªäººåšå®¢"
        imageUrl: "/apple-touch-icon.png"
        imageWidth: 180
        imageHeight: 180
        imageTitle: my image
        buttons:
            - name: Posts
              url: p
            - name: Tags
              url: tags
    homeInfoParams:
      #Title: "Hi ğŸ‘‹ æ¬¢è¿æ¥é€›é€›~ <br>å¯å…³æ³¨ Youtube Twitter ç”µæŠ¥ RSS å“”å“©å“”å“©..."
      Title: "Hi ğŸ‘‹ æ¬¢è¿æ¥é€›é€›~ <br>å¯å…³æ³¨ çŸ¥ä¹ RSS Telegram Twitter..."
        #Title: "PaperMod"
        #Content: >
            #Welcome to demo of hugo's theme PaperMod.

            #- **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.

            #- Do give a ğŸŒŸ on Github !

            #- PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

    #socialIcons:
        #- name: github
          #url: "https://github.com/adityatelange/hugo-PaperMod"
        #- name: KoFi
          #url: "https://ko-fi.com/adityatelange"
        #- name: RsS
          #url: "index.xml"

    #editPost:
        #URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
        #Text: "Suggest Changes" # edit text
        #appendFilePath: true # to append file path to Edit link

     #label:
         #text: "Home"
         #icon: icon.png
         #iconHeight: 35

     #analytics:
         #google:
             #SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

     #cover:
         #hidden: true # hide everywhere but not in structured data
         #hiddenInList: true # hide on list pages and home
         #hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true

pluralizeListTitles: false

#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

#privacy:
    #vimeo:
        #disabled: false
        #simple: true

    #twitter:
        #disabled: false
        #enableDNT: true
        #simple: true

    #instagram:
        #disabled: false
        #simple: true

    #youtube:
        #disabled: false
        #privacyEnhanced: true

#services:
    #instagram:
        #disableInlineCSS: true
    #twitter:
        #disableInlineCSS: true
